### ISSUE TITLE
Native autoscaling support

### ISSUE THREAD

**Issue by Elfocrash** [giorgited/CosmosScale#2]
Hey there,

First and foremost, good job on this.

I'm wondering, have you taken into account the fact that Cosmos DB will support native autoscaling soon? The Offer object already has the new autoscaling properties and the engine (at least the emulator) seems to do as well.

Mainly asking because I had a similar feature in Cosmonaut and I removed it because of that.

**Comment by giorgited** [comment]
Thank you sir! The Autoscale support was filled to MSFT on 10/2016 and has been set as "Started" since 11/2017. Although, I have observed that the Offer/OfferV2 object shows signs of started development, I don not yet plan on taking into the consideration that they may release this feature in near future. If they do, then I will see if my library still makes sense to serve its purpose and adjust things then.
